### ISSUE TITLE
Message history cannot scroll to bottom automatically

### ISSUE THREAD

**Issue by harryworld** [1request/weixin#3]
Cannot scroll to the bottom when a customer is selected, when there are already some messages

**Comment by harryworld** [comment]
Try using collection-hooks https://github.com/matb33/meteor-collection-hooks

`.after.find(userId, selector, options, cursor)`
https://github.com/matb33/meteor-collection-hooks#afterfinduserid-selector-options-cursor

**Comment by zuohaisu** [comment]
I think because there is a latency compensation.
