### ISSUE TITLE
cannot send msg from service center to user

### ISSUE THREAD

**Issue by zuohaisu** [1request/weixin#4]
everytime i press send button, the console display the content below: 

XMLHttpRequest cannot load http://54.91.146.250/kf. The 'Access-Control-Allow-Origin' header has a value 'http://localhost:4000' that is not equal to the supplied origin. Origin 'http://kf.xin.io' is therefore not allowed access.

**Comment by harryworld** [comment]
Refer to https://github.com/1request/weixin-rails/issues/1
