### ISSUE TITLE
cannot play voice msg

### ISSUE THREAD

**Issue by zuohaisu** [1request/weixin#6]
i tested my local test Environment.

**Comment by puiesabu** [comment]
28/6 9:24 api.xin.io 艾勤客服(服务号) 收到 Kaeli的voice msg

**Comment by zuohaisu** [comment]
我本地的console错误是：
Refused to load media from 'http://6e0109a1.ngrok.com/' because it violates the following Content Security Policy directive: "default-src 'self' http://localhost:3000". Note that 'media-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by zuohaisu** [comment]
应该是我的配置出了什么问题

**Comment by puiesabu** [comment]
因為meteor 的browser_policy.js 沒有 allow origin "http://6e0109a1.ngrok.com/"。 master branch 已經解決了這個問題，你可以在source tree merge master，之後media 和browser_policy.js 會使用development.json 內的origin
