### ISSUE TITLE
cannot receive the image msg

### ISSUE THREAD

**Issue by zuohaisu** [1request/weixin#8]
500 Internal Server Error, also my local environment.

**Comment by puiesabu** [comment]
28/6 9:22 api.xin.io 艾勤客服(服务号) 收到 Kaeli的image msg

**Comment by zuohaisu** [comment]
嗯，线上环境是可以的。

我的本地环境有这个错误：
这个是development log：--------------------------------------------------------------------
Completed 500 Internal Server Error in 1147ms

NoMethodError (undefined method `size' for nil:NilClass):
  app/uploaders/media_uploader.rb:40:in`rotate_image'
  app/decorators/controllers/weixin_rails_middleware/weixin_controller_decorator.rb:37:in `create_message'
  app/decorators/controllers/weixin_rails_middleware/weixin_controller_decorator.rb:97:in`response_image_message'
  app/decorators/controllers/weixin_rails_middleware/weixin_controller_decorator.rb:20:in `reply'

---

这个是console error：------------------------------------------------------------------------
Refused to load the image 'http://6e0109a1.ngrok.com/' because it violates the following Content Security Policy directive: "img-src data: 'self' http://wx.qlogo.cn http://localhost:3000".

**Comment by puiesabu** [comment]
Make sure imagemagick is installed. Try `brew install imagemagick`, `bundle` and restart your rails server
